### ISSUE TITLE
Tag editing does not save

### ISSUE THREAD

**Issue by jensz12** [kabouzeid/phonograph-issue-tracker#19]
When i use the Tag Edit to edit a song, it does not save it. Im on a HTC One (M8) Android 5.0.1 Sense 6

**Comment by CostaR26** [comment]
The same problem happens in my Motorola Moto G (XT1033)

**Comment by BohemianRahpGod** [comment]
Same here 2nd gen moto G, but I find it works if it's stored on the local storage, not SD card. It's not the app, cause other Tag editors do this as well

**Comment by jensz12** [comment]
I wont work for me on both internal storage and SD card

**Comment by kabouzeid** [comment]
Two problems main problems here:

1. for some reasons on some devices some file formats are not supported and I have no influence on that because I am using a 3rd party library for music tagging.
(btw, mp3 files should work on all devices)

2. On KitKat there is a bug which prevents write access to files located on the sdcard and on Lollipop the bug is only partially fixed.

=> I would always recommend tagging your music on the pc as it is much faster. In case you still want to edit it inside the app make sure you use mp3 files and the files are located on the internal storage.
